# This workflow tests if the commit or pr meets the requirements and deploys to
# a development server upon success.
# It assumes that `npm install`, `composer install` and `npx grunt release` are valid commands.
# The action expects a valid zip file in the `./update/` folder and the `slug` key in the
# `package.json` to be set.
name: üß™ Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: ‚öôÔ∏è Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: üíæ Get node.js cache directory
        id: node-cache-dir
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT # Use $(yarn cache dir) for yarn

      - name: üíæ Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.node-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} # Use '**/yarn.lock' for yarn
          restore-keys: ${{ runner.os }}-node-

      - name: üíæ Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: ‚öôÔ∏è Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: üßπ Lint the code
        run: npm run lint

      - name: üöÄ Start the environment
        run: npm start

      - name: üß™ Run tests
        run: npm test

      - name: üö¢ Deploy plugin to InstaWP
        if: ${{ github.event_name == 'push' && success() }}
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.INSTAWP_PRIVATE_KEY }}
          SOURCE: "./plugin/"
          REMOTE_HOST: ${{ secrets.INSTAWP_SFTP_HOST }}
          REMOTE_USER: ${{ secrets.INSTAWP_SFTP_USER }}
          TARGET: /home/${{ secrets.INSTAWP_SFTP_USER }}/web/${{ secrets.INSTAWP_SFTP_HOST }}/public_html/wp-content/plugins/lhpbpp/

      - name: üö¢ Deploy theme to InstaWP
        if: ${{ github.event_name == 'push' && success() }}
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.INSTAWP_PRIVATE_KEY }}
          SOURCE: "./theme/"
          REMOTE_HOST: ${{ secrets.INSTAWP_SFTP_HOST }}
          REMOTE_USER: ${{ secrets.INSTAWP_SFTP_USER }}
          TARGET: /home/${{ secrets.INSTAWP_SFTP_USER }}/web/${{ secrets.INSTAWP_SFTP_HOST }}/public_html/wp-content/themes/lhpbpt/
